# Generated by Django 3.2.6 on 2021-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_product.jpg', upload_to='profile_photo'),
        ),
    ]
