# Generated by Django 3.2.6 on 2021-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210828_1706'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user_rated', 'user_received'), name='one_rating_per_user'),
        ),
    ]
