# Generated by Django 3.2.6 on 2021-08-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slau',
            new_name='slug',
        ),
    ]
