# Generated by Django 3.2.6 on 2021-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('О', 'Одежда'), ('И', 'Игрушки'), ('Т', 'Транспорт'), ('У', 'Услуга'), ('М', 'Мебель'), ('Ж', 'Жилье'), ('ДЖ', 'Домашние животные'), ('ТЭ', 'Техника и электроника')], max_length=250),
        ),
    ]
