# Generated by Django 3.2.6 on 2021-08-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
    ]
