# Generated by Django 3.2.6 on 2021-09-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210905_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_profile',
            new_name='author',
        ),
    ]
