# Generated by Django 3.2.6 on 2021-08-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
