# Generated by Django 3.2.6 on 2021-09-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210906_1432'),
        ('products', '0007_alter_product_image'),
    ]

    operations = [
    ]
