# Generated by Django 3.2.6 on 2021-08-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210813_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Одежда', 'O'), ('Транспорт', 'Т'), ('Услуги', 'У'), ('Игрушки', 'И'), ('Мебель', 'М'), ('Электроника', 'Э')], max_length=250),
        ),
    ]
