# Generated by Django 3.2.6 on 2021-08-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='Договорная', max_length=255),
        ),
    ]
