# Generated by Django 3.2.6 on 2021-09-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210906_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
