# Generated by Django 3.2.6 on 2021-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210813_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Одеж', 'Oдежда'), ('Трант', 'Транспорт'), ('Усл', 'Услуги'), ('Игруш', 'Игрушки'), ('Меб', 'Мебель'), ('Элект', 'Электроника')], max_length=250),
        ),
    ]
