# Generated by Django 3.2.6 on 2021-08-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('products', '0002_rename_slau_category_slug'),
        ('products', '0012_alter_category_name'),
    ]

    operations = [
    ]
