# Generated by Django 3.2.6 on 2021-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_photo'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
