# Generated by Django 3.2.6 on 2021-08-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_slau_category_slug'),
        ('products', '0013_merge_20210816_1641'),
    ]

    operations = [
    ]
