# Generated by Django 3.2.6 on 2021-08-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_profile',
        ),
    ]
